// ─────────────────────────────────────────────
//  GENERATED FILE - do not edit by hand.
//  Regenerate:  python3 scripts/import_pharma.py
//  Source:      Jaydev Group Product list.xlsx
//
//  Pharmacopoeia grade, DMF, CEP and GMP status are NOT in the source
//  sheet and are deliberately absent here rather than guessed. The UI
//  renders "Grade & documentation on request" until they are supplied.
// ─────────────────────────────────────────────

export type PharmaSection = 'apis' | 'intermediates' | 'ingredients' | 'excipients' | 'others';
export type PharmaProduct = {
  id: string;
  /** Full chemical name. Always searchable, even when shortName is shown. */
  name: string;
  /** Trade name shown on cards, from data/pharma-short-names.json. */
  shortName?: string;
  section: PharmaSection;
  cas?: string;
  /** Set when the product is sold in more than one isomeric form. */
  casForms?: { label: string; cas: string }[];
  /** APIs only - the therapeutic filter axis. */
  therapeuticSegment?: string;
  investigational?: boolean;
};

/** What a card and the search index display. */
export const displayName = (p: PharmaProduct) => p.shortName ?? p.name;

export const PHARMA_SECTIONS: { id: PharmaSection; label: string }[] = [
  { id: "apis", label: "APIs" },
  { id: "intermediates", label: "Intermediates" },
  { id: "ingredients", label: "Nutraceutical Ingredients" },
  { id: "excipients", label: "Pharmaceutical Excipients" },
  { id: "others", label: "Fine Chemicals & Others" },
];

export const THERAPEUTIC_SEGMENTS: { id: string; label: string }[] = [
  { id: "amino-acids-nutrition", label: "Amino Acids / Nutrition" },
  { id: "anesthesia-hospital", label: "Anesthesia / Hospital" },
  { id: "anti-infective", label: "Anti-infective" },
  { id: "anticoagulants", label: "Anticoagulants" },
  { id: "cns-psychiatry", label: "CNS / Psychiatry" },
  { id: "cardiovascular", label: "Cardiovascular" },
  { id: "dermatology", label: "Dermatology" },
  { id: "gi-liver", label: "GI / Liver" },
  { id: "metabolic-obesity", label: "Metabolic / Obesity" },
  { id: "oncology", label: "Oncology" },
  { id: "pain-anti-inflammatory", label: "Pain / Anti-inflammatory" },
  { id: "peptide-building-blocks", label: "Peptide / Building Blocks" },
  { id: "respiratory-steroids", label: "Respiratory / Steroids" },
  { id: "specialty-ingredients", label: "Specialty Ingredients" },
  { id: "veterinary", label: "Veterinary" },
];

export const pharmaProducts: PharmaProduct[] = [
  {"id": "paclitaxel", "name": "Paclitaxel", "section": "apis", "cas": "33069-62-4", "therapeuticSegment": "Oncology"},
  {"id": "darolutamide", "name": "Darolutamide", "section": "apis", "cas": "1297538-32-9", "therapeuticSegment": "Oncology"},
  {"id": "abemaciclib", "name": "Abemaciclib", "section": "apis", "cas": "1231929-97-7", "therapeuticSegment": "Oncology"},
  {"id": "fludarabine-phosphate", "name": "Fludarabine Phosphate", "section": "apis", "cas": "75607-67-9", "therapeuticSegment": "Oncology"},
  {"id": "calcium-folinate", "name": "Calcium folinate", "section": "apis", "cas": "1492-18-8", "therapeuticSegment": "Oncology"},
  {"id": "gemcitabine", "name": "Gemcitabine", "section": "apis", "cas": "95058-81-4", "therapeuticSegment": "Oncology"},
  {"id": "regorafenib", "name": "Regorafenib", "section": "apis", "cas": "755037-03-7", "therapeuticSegment": "Oncology"},
  {"id": "olaparib", "name": "Olaparib", "section": "apis", "cas": "763113-22-0", "therapeuticSegment": "Oncology"},
  {"id": "vinorelbine-tartrate", "name": "Vinorelbine tartrate", "section": "apis", "cas": "125317-39-7", "therapeuticSegment": "Oncology"},
  {"id": "suzetrigine", "name": "Suzetrigine", "section": "apis", "cas": "2649467-58-1", "therapeuticSegment": "CNS / Psychiatry"},
  {"id": "lemborexant", "name": "Lemborexant", "section": "apis", "cas": "1369764-02-2", "therapeuticSegment": "CNS / Psychiatry"},
  {"id": "sertraline-hydrochloride", "name": "Sertraline hydrochloride", "section": "apis", "cas": "79559-97-0", "therapeuticSegment": "CNS / Psychiatry"},
  {"id": "d-serine", "name": "D-serine", "section": "apis", "cas": "312-84-5", "therapeuticSegment": "CNS / Psychiatry"},
  {"id": "samidorphan-l-malate", "name": "Samidorphan L-malate", "section": "apis", "cas": "1204592-75-5", "therapeuticSegment": "CNS / Psychiatry"},
  {"id": "lumateperone-tosylate", "name": "Lumateperone Tosylate", "section": "apis", "cas": "1187020-80-9", "therapeuticSegment": "CNS / Psychiatry"},
  {"id": "resmetirom", "name": "Resmetirom", "section": "apis", "cas": "920509-32-6", "therapeuticSegment": "Metabolic / Obesity"},
  {"id": "tirzepatide", "name": "Tirzepatide", "section": "apis", "cas": "2023788-19-2", "therapeuticSegment": "Metabolic / Obesity"},
  {"id": "naldemedine", "name": "Naldemedine", "section": "apis", "cas": "1345728-04-2", "therapeuticSegment": "GI / Liver"},
  {"id": "teprenone", "name": "Teprenone", "section": "apis", "cas": "6809-52-5", "therapeuticSegment": "GI / Liver"},
  {"id": "ursodeoxycholic-acid", "name": "Ursodeoxycholic Acid", "section": "apis", "cas": "128-13-2", "therapeuticSegment": "GI / Liver"},
  {"id": "mesalamine", "name": "Mesalamine", "section": "apis", "cas": "89-57-6", "therapeuticSegment": "GI / Liver"},
  {"id": "amlexanox", "name": "Amlexanox", "section": "apis", "cas": "68302-57-8", "therapeuticSegment": "Dermatology"},
  {"id": "calcipotriol-monohydrate", "name": "Calcipotriol Monohydrate", "section": "apis", "cas": "147657-22-5", "therapeuticSegment": "Dermatology"},
  {"id": "clobetasol-propionate", "name": "Clobetasol propionate", "section": "apis", "cas": "25122-46-7", "therapeuticSegment": "Dermatology"},
  {"id": "mupirocin", "name": "Mupirocin", "section": "apis", "cas": "12650-69-0", "therapeuticSegment": "Anti-infective"},
  {"id": "cagrilintide", "name": "Cagrilintide", "section": "apis", "cas": "1415456-99-3", "therapeuticSegment": "Metabolic / Obesity", "investigational": true},
  {"id": "retatrutide", "name": "Retatrutide", "section": "apis", "cas": "2381089-83-2", "therapeuticSegment": "Metabolic / Obesity", "investigational": true},
  {"id": "z-d-thr-oh", "name": "Z-D-THR-OH", "section": "apis", "cas": "80384-27-6", "therapeuticSegment": "Peptide / Building Blocks"},
  {"id": "fmoc-d-thr-oh", "name": "FMOC-D_THR_OH", "section": "apis", "cas": "157355-81-2", "therapeuticSegment": "Peptide / Building Blocks"},
  {"id": "fluvastatin-sodium", "name": "Fluvastatin Sodium", "section": "apis", "cas": "93957-55-2", "therapeuticSegment": "Cardiovascular"},
  {"id": "benazepril-hcl", "name": "Benazepril HCL", "section": "apis", "cas": "86541-74-4", "therapeuticSegment": "Cardiovascular"},
  {"id": "simvastatin", "name": "Simvastatin", "section": "apis", "cas": "79902-63-9", "therapeuticSegment": "Cardiovascular"},
  {"id": "fenofibrate", "name": "Fenofibrate", "section": "apis", "cas": "49562-28-9", "therapeuticSegment": "Cardiovascular"},
  {"id": "sacubitril-sodium", "name": "Sacubitril Sodium", "section": "apis", "cas": "149690-05-1", "therapeuticSegment": "Cardiovascular"},
  {"id": "entecavir-monohydrate", "name": "Entecavir Monohydrate", "section": "apis", "cas": "209216-23-9", "therapeuticSegment": "Anti-infective"},
  {"id": "clindamycin-palmitate-hydrochloride", "name": "Clindamycin palmitate hydrochloride", "section": "apis", "cas": "25507-04-4", "therapeuticSegment": "Anti-infective"},
  {"id": "azithromycin", "name": "Azithromycin", "section": "apis", "cas": "117772-70-0", "therapeuticSegment": "Anti-infective"},
  {"id": "neomycin-sulfate", "name": "Neomycin sulfate", "section": "apis", "cas": "1405-10-3", "therapeuticSegment": "Anti-infective"},
  {"id": "acyclovir", "name": "Acyclovir", "section": "apis", "cas": "59277-89-3", "therapeuticSegment": "Anti-infective"},
  {"id": "oseltamivir-phosphate", "name": "Oseltamivir Phosphate", "section": "apis", "cas": "204255-11-8", "therapeuticSegment": "Anti-infective"},
  {"id": "maribavir", "name": "Maribavir", "section": "apis", "cas": "176161-24-3", "therapeuticSegment": "Anti-infective"},
  {"id": "letermovir", "name": "Letermovir", "section": "apis", "cas": "917389-32-3", "therapeuticSegment": "Anti-infective"},
  {"id": "clindamycin-phosphate", "name": "Clindamycin Phosphate", "section": "apis", "cas": "24729-96-2", "therapeuticSegment": "Anti-infective"},
  {"id": "levofloxacin-hemihydrate", "name": "Levofloxacin Hemihydrate", "section": "apis", "cas": "138199-71-0", "therapeuticSegment": "Anti-infective"},
  {"id": "tigecycline", "name": "Tigecycline", "section": "apis", "cas": "220620-09-7", "therapeuticSegment": "Anti-infective"},
  {"id": "furantoin", "name": "Furantoin", "section": "apis", "cas": "67-20-9", "therapeuticSegment": "Anti-infective"},
  {"id": "posaconazole", "name": "Posaconazole", "section": "apis", "cas": "171228-49-2", "therapeuticSegment": "Anti-infective"},
  {"id": "sulbactam-pivoxil", "name": "Sulbactam pivoxil", "section": "apis", "cas": "69388-79-0", "therapeuticSegment": "Anti-infective"},
  {"id": "edetate-disodium", "name": "Edetate Disodium", "section": "apis", "cas": "6381-92-6", "therapeuticSegment": "Specialty Ingredients"},
  {"id": "peg-3350-4000-6000-20000", "name": "PEG 3350/4000/6000/20000", "section": "apis", "cas": "25322-68-3", "therapeuticSegment": "Specialty Ingredients"},
  {"id": "icodextrin", "name": "Icodextrin", "section": "apis", "cas": "337376-15-5", "therapeuticSegment": "Specialty Ingredients"},
  {"id": "hydroxyethyl-starch-130-0-4", "name": "Hydroxyethyl starch 130/0.4", "section": "apis", "cas": "9005-27-0", "therapeuticSegment": "Specialty Ingredients"},
  {"id": "indometacin", "name": "Indometacin", "section": "apis", "cas": "53-86-1", "therapeuticSegment": "Pain / Anti-inflammatory"},
  {"id": "loxoprofen-sodium", "name": "Loxoprofen Sodium", "section": "apis", "cas": "80382-23-6", "therapeuticSegment": "Pain / Anti-inflammatory"},
  {"id": "diclofenac-sodium", "name": "Diclofenac Sodium", "section": "apis", "cas": "15307-79-6", "therapeuticSegment": "Pain / Anti-inflammatory"},
  {"id": "piroxicam", "name": "Piroxicam", "section": "apis", "cas": "36322-90-4", "therapeuticSegment": "Pain / Anti-inflammatory"},
  {"id": "propofol", "name": "Propofol", "section": "apis", "cas": "2078-54-8", "therapeuticSegment": "Anesthesia / Hospital"},
  {"id": "dexmedetomidine-hydrochloride", "name": "Dexmedetomidine Hydrochloride", "section": "apis", "cas": "145108-58-3", "therapeuticSegment": "CNS / Psychiatry"},
  {"id": "mepivacaine-hydrochloride", "name": "Mepivacaine Hydrochloride", "section": "apis", "cas": "1722-62-9", "therapeuticSegment": "Anesthesia / Hospital"},
  {"id": "oxybuprocaine-hydrochloride", "name": "Oxybuprocaine Hydrochloride", "section": "apis", "cas": "5987-82-6", "therapeuticSegment": "Anesthesia / Hospital"},
  {"id": "tilmicosin", "name": "Tilmicosin", "section": "apis", "cas": "108050-54-0", "therapeuticSegment": "Anti-infective"},
  {"id": "flunixin-meglumine", "name": "Flunixin meglumine", "section": "apis", "cas": "42461-84-7", "therapeuticSegment": "Pain / Anti-inflammatory"},
  {"id": "afoxolaner", "name": "Afoxolaner", "section": "apis", "cas": "1093861-60-9", "therapeuticSegment": "Veterinary"},
  {"id": "moxidectin", "name": "Moxidectin", "section": "apis", "cas": "113507-06-5", "therapeuticSegment": "Veterinary"},
  {"id": "selamectin", "name": "Selamectin", "section": "apis", "cas": "220119-17-5", "therapeuticSegment": "Veterinary"},
  {"id": "fluralaner", "name": "Fluralaner", "section": "apis", "cas": "864731-61-3", "therapeuticSegment": "Veterinary"},
  {"id": "propetamphos", "name": "Propetamphos", "section": "apis", "cas": "31218-83-4", "therapeuticSegment": "Veterinary"},
  {"id": "maropitant-citrate-hydrate", "name": "Maropitant citrate hydrate", "section": "apis", "cas": "359875-09-5", "therapeuticSegment": "Veterinary"},
  {"id": "marbofloxacine", "name": "Marbofloxacine", "section": "apis", "cas": "115550-35-1", "therapeuticSegment": "Anti-infective"},
  {"id": "l-leucine", "name": "L-Leucine", "section": "apis", "cas": "61-90-5", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "glycine", "name": "Glycine", "section": "apis", "cas": "56-40-6", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-lysine", "name": "L-Lysine", "section": "apis", "cas": "56-87-1", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-methionine", "name": "L-Methionine", "section": "apis", "cas": "63-68-3", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-phenylalanine", "name": "L-Phenylalanine", "section": "apis", "cas": "63-91-2", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-alanine", "name": "L-Alanine", "section": "apis", "cas": "56-41-7", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-tryptophan", "name": "L-Tryptophan", "section": "apis", "cas": "73-22-3", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-threonine", "name": "L-Threonine", "section": "apis", "cas": "72-19-5", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-serine", "name": "L-serine", "section": "apis", "cas": "56-45-1", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-valine", "name": "L-valine", "section": "apis", "cas": "72-18-4", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-glutamic-acid", "name": "L-Glutamic Acid", "section": "apis", "cas": "56-86-0", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-arginine", "name": "L-Arginine", "section": "apis", "cas": "74-79-3", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-cysteine", "name": "L-Cysteine", "section": "apis", "cas": "52-90-4", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-histidine", "name": "L-Histidine", "section": "apis", "cas": "71-00-1", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "branched-chain-amino-acids", "name": "Branched-chain Amino Acids", "section": "apis", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "l-arginine-l-aspartate", "name": "L-arginine-L-Aspartate", "section": "apis", "cas": "7675-83-4", "therapeuticSegment": "Amino Acids / Nutrition"},
  {"id": "d-threonine", "name": "D-Threonine", "section": "apis", "cas": "632-20-2"},
  {"id": "n-acetyl-dl-l-leucine", "name": "N-Acetyl-DL(L)-Leucine", "section": "apis", "cas": "1188-21-2"},
  {"id": "cetrorelix-acetate", "name": "Cetrorelix Acetate", "section": "apis", "cas": "120287-85-6"},
  {"id": "mycophenolate-mofetil", "name": "Mycophenolate mofetil", "section": "apis", "cas": "128794-94-5"},
  {"id": "promethazine-hydrochloride", "name": "Promethazine Hydrochloride", "section": "apis", "cas": "58-33-3"},
  {"id": "allopurinol", "name": "Allopurinol", "section": "apis", "cas": "315-30-0"},
  {"id": "8dm-16-beta-methyl-epoxide", "name": "8DM;16-beta Methyl Epoxide", "section": "intermediates", "cas": "24916-90-3"},
  {"id": "db11", "name": "DB11", "section": "intermediates", "cas": "981-34-0"},
  {"id": "prednisolone", "name": "Prednisolone", "section": "intermediates", "cas": "50-24-8"},
  {"id": "6-9-difluoro-16-methyl-11-17-21-trihydroxy-1-4-pregnadiene-3-20-dione", "name": "6α,9α-difluoro-16α-methyl-11β,17α,21-trihydroxy-1,4-pregnadiene-3,20-dione", "section": "intermediates", "cas": "2135-17-3", "shortName": "Flumethasone"},
  {"id": "2-2-3-2-7-chloro-2-quinolinyl-ethenylphenyl-3-hydroxypropyl-2-propanol", "name": "2-(2-(3-(2-(7-chloro-2-quinolinyl)-ethenylphenyl)-3-hydroxypropyl)-2-propanol", "section": "intermediates", "cas": "142569-70-8", "shortName": "Montelukast intermediate"},
  {"id": "2-1-mercaptomethyl-cyclopropyl-acetic-acid", "name": "2-[1-(Mercaptomethyl) cyclopropyl]acetic acid", "section": "intermediates", "cas": "162515-68-6"},
  {"id": "4-methoxy-alpha-methyl-n-phenylmethyl-benzeneethanamine-hydrochloride", "name": "4-Methoxy-alpha-methyl-n-(phenylmethyl)benzeneethanamine hydrochloride", "section": "intermediates", "cas": "1049695-95-5", "shortName": "Formoterol intermediate"},
  {"id": "n-5-1r-2-bromo-1-hydroxyethyl-2-phenylmethoxy-phenyl-carboxamide", "name": "N-[5-((1R)-2-bromo-1-hydroxyethyl)-2-(phenylmethoxy)phenyl]carboxamide", "section": "intermediates", "cas": "201677-59-0", "shortName": "Formoterol intermediate"},
  {"id": "5-2r-2-oxiranyl-8-benzyloxy-2-1h-quinolonone", "name": "5-(2R)-2-Oxiranyl-8--benzyloxy-2(1H)-quinolonone", "section": "intermediates", "cas": "173140-90-4"},
  {"id": "n-5-acetyl-6-ethyl-2-3-dihydro-1h-inden-2-yl-2-2-2-trifluoro-acetamide", "name": "N-(5-acetyl-6-ethyl-2,3-dihydro-1H-inden-2-yl)-2,2,2-trifluoro-acetamide", "section": "intermediates", "cas": "601487-89-2", "shortName": "Indanyl trifluoroacetamide"},
  {"id": "2-methylamino-pyridine-3-methanol", "name": "2-(Methylamino)pyridine-3-methanol", "section": "intermediates", "cas": "32399-12-5"},
  {"id": "4-2-bromoacetyl-benzonitrile", "name": "4-(2-Bromoacetyl)Benzonitrile", "section": "intermediates", "cas": "20099-89-2"},
  {"id": "2r-3r-3-2-5-difluorophenyl-3-hydroxy-2-methyl-4-1h-1-2-4-triazol-1-yl-", "name": "(2R,3R)-3-(2,5-Difluorophenyl)-3-Hydroxy-2-Methyl-4-(1H-1,2,4-Triazol-1-yl)Thiobutyramide", "section": "intermediates", "cas": "368421-58-3", "shortName": "Isavuconazole intermediate"},
  {"id": "4-chloro-6-ethyl-5-fluoropyrimidine", "name": "4-Chloro-6-ethyl-5-fluoropyrimidine", "section": "intermediates", "cas": "137234-74-3"},
  {"id": "acetoxy-empagliflozin", "name": "Acetoxy Empagliflozin", "section": "intermediates", "cas": "915095-99-7"},
  {"id": "dapagliflozin-tetraacetate", "name": "Dapagliflozin Tetraacetate", "section": "intermediates", "cas": "461432-25-7"},
  {"id": "2s-1-chloroacetyl-2-pyrrolidinecarbonitrile", "name": "(2S)-1-(Chloroacetyl)-2-pyrrolidinecarbonitrile", "section": "intermediates", "cas": "207557-35-5"},
  {"id": "sitagliptin-base", "name": "Sitagliptin base", "section": "intermediates", "cas": "486460-32-6"},
  {"id": "n-amino-3-azabicyclo-3-3-0-octan-hcl", "name": "N-amino-3-azabicyclo[3,3,0]-Octan HCl", "section": "intermediates", "cas": "58108-05-7"},
  {"id": "2-3ar-4s-6r-6as-6-amino-2-2-dimethyltetrahydro-3ah-cyclopenta-d-1-3-di", "name": "2-((3aR,4S,6R,6aS)-6-amino-2,2-dimethyltetrahydro-3ah-cyclopenta[d][1,3]dioxol-4-yloxy)ethanol L-tataric acid", "section": "intermediates", "cas": "376608-65-0", "shortName": "Ticagrelor intermediate"},
  {"id": "1r-2s-2-3-4-difluorophenyl-cyclopropanamine-2r-hydroxy-phenyl-ethanoat", "name": "(1R,2S)-2-(3,4-difluorophenyl)cyclopropanamine(2R)-Hydroxy(phenyl)ethanoate", "section": "intermediates", "cas": "376608-71-8", "shortName": "Ticagrelor intermediate"},
  {"id": "4-6-dichloro-2-propylthiopyrimidine-5-amine", "name": "4,6-dichloro-2-propylthiopyrimidine-5-amine", "section": "intermediates", "cas": "145783-15-9"},
  {"id": "tert-butyl-4-formyl-5-methoxy-7-methyl-1h-indole-1-carboxylate", "name": "Tert-Butyl 4-formyl-5-methoxy-7-methyl-1H-indole-1-carboxylate", "section": "intermediates", "cas": "1481631-51-9", "shortName": "Methoxy-methyl indole carboxylate, Boc"},
  {"id": "r-3-amino-1-butanol", "name": "R-3-amino-1-butanol", "section": "intermediates", "cas": "61477-40-5"},
  {"id": "4-pyrimidinecarboxylic-acid-1-6-dihydro-5-hydroxy-2-1-methyl-1-phenylm", "name": "4-pyrimidinecarboxylic acid,1,6-dihydro-5-hydroxy-2-[1-methyl-1-[[(phenylmethoxy)carbonyl]amino]ethyl]-6-oxo-methyl ester", "section": "intermediates", "cas": "519032-08-7", "shortName": "Raltegravir intermediate"},
  {"id": "4-chloro-1-2-methylpropyl-1h-imidazo-4-5-c-quinoline", "name": "4-chloro-1-(2-methylpropyl)-1H-imidazo[4,5-c]quinoline", "section": "intermediates", "cas": "99010-64-7"},
  {"id": "3r-4s-3-2-bromoacetyl-4-ethyl-1-pyrrolidinecarboxylic-acid-phenylmethy", "name": "(3R,4S)-3-(2-Bromoacetyl)-4-ethyl-1 pyrrolidinecarboxylic acid phenylmethyl ester", "section": "intermediates", "cas": "1428243-26-8", "shortName": "Upadacitinib intermediate"},
  {"id": "n-5-4-methylphenyl-sulfonyl-5h-pyrrolo-2-3-b-pyrazin-2-yl-carbamic-aci", "name": "N-[5-[(4-Methylphenyl)sulfonyl]-5H-pyrrolo[2,3-b]pyrazin 2-yl]carbamic acid ethyl ester", "section": "intermediates", "cas": "1869118-24-0", "shortName": "Upadacitinib intermediate"},
  {"id": "4-phenoxybenzoic-acid", "name": "4-Phenoxybenzoic Acid", "section": "intermediates", "cas": "2215-77-2"},
  {"id": "s-1-boc-3-hydroxypiperidine", "name": "(S)-1-Boc-3-hydroxypiperidine", "section": "intermediates", "cas": "143900-44-1"},
  {"id": "4-hydroxy-1-methyl-7-phenoxy-3-isoquinolinecarboxylic-acid-ethyl-ester", "name": "4-Hydroxy-1-methyl-7-phenoxy-3-isoquinolinecarboxylic acid ethyl ester", "section": "intermediates", "cas": "1809286-36-9", "shortName": "Roxadustat intermediate"},
  {"id": "erbium-hydroxide", "name": "Erbium hydroxide", "section": "intermediates", "cas": "138401-24-8"},
  {"id": "2-2-6-difluorobenzyl-ethoxycarbonyl-amino-4-dimethylamino-methyl-5-4-n", "name": "(2-((2,6-difluorobenzyl)(ethoxycarbonyl)amino)-4-((dimethylamino)methyl)-5-(4-nitrophenyl)thiophene-3-carboxylic acid", "section": "intermediates", "cas": "1589503-95-6", "shortName": "Relugolix intermediate"},
  {"id": "5h-pyrazolo-4-3-c-pyridine-5-carboxylic-acid-3-amino-2-4-fluoro3-5-dim", "name": "5H-Pyrazolo[4,3-c]pyridine-5-carboxylic acid, 3-amino-2-(4-fluoro3,5-dimethylphenyl)-2,4,6,7-tetrahydro-4-methyl-1,1-dimethylethyl ester,(4s)-", "section": "intermediates", "cas": "2212021-59-3", "shortName": "Pyrazolopyridine carboxylate, Boc"},
  {"id": "s-1-4-fluoro-1-methyl-1-h-indazol-5-yl-3-2-4-fluoro-3-5-dimethylphenyl", "name": "(s)-1-(4-fluoro-1-methyl-1 H-indazol-5-yl)-3-(2-(4-fluoro-3,5-dimethylphenyl)-4-methyl-4,5,6,7-tetrahydro-2H-pyrazoloB,3-c]pyridin-3-yl)-1 H-imidazol-2(3H)-one hydrochloride", "section": "intermediates", "cas": "2212022-57-4", "shortName": "Pyrazolopyridine imidazolone, HCl"},
  {"id": "2-2-dimethyl-4h-benzo-d-1-3-dioxin-6-yl-oxazolidin-2-one", "name": "(2,2-Dimethyl-4H-benzo[d][1,3]dioxin-6-yl)oxazolidin-2-one", "section": "intermediates", "cas": "452339-73-0", "shortName": "Benzodioxinyl oxazolidinone"},
  {"id": "6-bromohexyl-oxy-ethoxy-methyl-1-3-dichlorobenzene", "name": "((6-Bromohexyl)oxy)ethoxy)methyl)-1,3-dichlorobenzene", "section": "intermediates", "cas": "503070-57-3"},
  {"id": "1-fluoronaphthalene", "name": "1-Fluoronaphthalene", "section": "intermediates", "cas": "321-38-0"},
  {"id": "11-17-dihydroxy-6-methylpregna-1-4-diene-3-20-dione", "name": "11β,17α-Dihydroxy-6α-methylpregna-1,4-diene-3,20-dione", "section": "intermediates", "cas": "6870-94-6", "shortName": "Methylprednisolone intermediate"},
  {"id": "11-16-17-21-tetrahydroxypregna-1-4-diene-3-20-dione", "name": "11β,16α,17,21-tetrahydroxypregna-1,4-diene-3,20-dione", "section": "intermediates", "cas": "13951-70-7"},
  {"id": "7-keto-lithocholic-acid", "name": "7-keto-lithocholic acid", "section": "intermediates", "cas": "4651-67-6"},
  {"id": "2-bromo-thiophene", "name": "2-Bromo Thiophene", "section": "intermediates", "cas": "1003-09-4"},
  {"id": "4-octylphenethyl-methanesulfonate", "name": "4-Octylphenethyl methanesulfonate", "section": "intermediates", "cas": "162358-06-7"},
  {"id": "1-2-iodoethyl-4-octylbenzen", "name": "1-(2-Iodoethyl)-4-octylbenzen", "section": "intermediates", "cas": "162358-06-7"},
  {"id": "1-phenyloctane", "name": "1-Phenyloctane", "section": "intermediates", "cas": "2189-60-8"},
  {"id": "diethyl-2-acetamido-2-4-octylphenethyl-malonate", "name": "Diethyl 2-acetamido-2-(4-octylphenethyl)malonate", "section": "intermediates", "cas": "162358-08-9"},
  {"id": "5-2-fluorophenyl-1-h-pyrrole-3-carbonitrile", "name": "5-(2-fluorophenyl)-1 H-pyrrole-3-carbonitrile", "section": "intermediates", "cas": "1240948-77-9"},
  {"id": "pyridine-3-sulfonyl-chloride-hydrochloride", "name": "Pyridine-3-sulfonyl chloride hydrochloride", "section": "intermediates", "cas": "16133-25-8"},
  {"id": "2-2-amino-5-bromobenzoyl-pyridine", "name": "2-(2-amino-5-bromobenzoyl)pyridine", "section": "intermediates", "cas": "1563-56-0"},
  {"id": "3-1-dimethylamino-ethyl-phenol", "name": "3-[1-(Dimethylamino) ethyl]phenol", "section": "intermediates", "cas": "105601-04-5"},
  {"id": "3-1s-1-dimethylaminoethyl-phenol", "name": "3-[(1S)-1-(Dimethylaminoethyl)]phenol", "section": "intermediates", "cas": "139306-10-8"},
  {"id": "3-1r-1-dimethylamino-ethyl-phenol", "name": "3-[(1R)-1-(Dimethylamino)ethyl)]phenol", "section": "intermediates", "cas": "851086-95-8"},
  {"id": "5-methoxy-1-4-trifluoromethyl-phenyl-1-pentanone", "name": "5-Methoxy-1-[4-(trifluoromethyl)phenyl)-1-pentanone", "section": "intermediates", "cas": "61718-80-7"},
  {"id": "2-6-dioxopiperidine-3-ammonium-chloride", "name": "2,6-Dioxopiperidine-3-ammonium chloride", "section": "intermediates", "cas": "24666-56-6"},
  {"id": "methyl-2-bromomethyl-3-nitrobenzoate", "name": "Methyl 2-bromomethyl-3-nitrobenzoate", "section": "intermediates", "cas": "98475-07-1"},
  {"id": "methyl-2-2-difluoro-2-fluorosulfonyl-acetate", "name": "Methyl 2,2-difluoro-2-(fluorosulfonyl)acetate", "section": "intermediates", "cas": "915095-99-7"},
  {"id": "3-3-3-trifluoro-2-2-dimethylpropionic-acid", "name": "3,3,3-Trifluoro-2,2-dimethylpropionic Acid", "section": "intermediates", "cas": "461432-25-7"},
  {"id": "2-6-dichloro-4-methyl-3-trifluoromethyl-pyridine", "name": "2,6-dichloro-4-methyl-3-(trifluoromethyl)pyridine", "section": "intermediates", "cas": "2384354-63-4"},
  {"id": "2-2-difluoropropionic-acid-ethyl-ester", "name": "2,2-difluoropropionic acid ethyl ester", "section": "intermediates", "cas": "28781-85-3"},
  {"id": "4-4-difluorocyclohexanecarboxylic-acid", "name": "4,4-Difluorocyclohexanecarboxylic acid", "section": "intermediates", "cas": "122665-97-8"},
  {"id": "3-3-difluorocyclobutanecarboxylic-acid", "name": "3,3-Difluorocyclobutanecarboxylic acid", "section": "intermediates", "cas": "107496-54-8"},
  {"id": "coenzyme-q10", "name": "Coenzyme Q10", "section": "ingredients", "cas": "303-98-0"},
  {"id": "vitamin-b12", "name": "Vitamin B12", "section": "ingredients", "cas": "68-19-9"},
  {"id": "vitamin-d3-40miu", "name": "Vitamin D3 40MIU", "section": "ingredients", "cas": "67-97-0"},
  {"id": "alpha-lipoic-acid", "name": "Alpha-lipoic Acid", "section": "ingredients", "cas": "1077-28-7"},
  {"id": "fish-oil", "name": "Fish oil", "section": "ingredients", "cas": "8016-13-5"},
  {"id": "l-carnosine", "name": "L-Carnosine", "section": "ingredients", "cas": "305-84-0"},
  {"id": "creatine-monohydrate", "name": "Creatine Monohydrate", "section": "ingredients", "cas": "6020-87-7"},
  {"id": "argireline", "name": "Argireline", "section": "ingredients", "cas": "616204-22-9"},
  {"id": "copper-peptide", "name": "Copper Peptide", "section": "ingredients", "cas": "49557-75-7"},
  {"id": "ergothioneine-egt", "name": "Ergothioneine, EGT", "section": "ingredients", "cas": "497-30-3"},
  {"id": "sodium-hyaluronate", "name": "Sodium hyaluronate", "section": "ingredients", "cas": "9067-32-7"},
  {"id": "spermidine-trihydrochloride", "name": "Spermidine trihydrochloride", "section": "ingredients", "cas": "334-50-9"},
  {"id": "natural-9-cis-b-carotene-dunaliella-salina", "name": "Natural 9-cis B-Carotene(Dunaliella salina)", "section": "ingredients", "cas": "13312-52-2"},
  {"id": "l-carnitine-l-tartrate", "name": "L-Carnitine L-Tartrate", "section": "ingredients", "cas": "36687-82-8"},
  {"id": "folic-acid", "name": "Folic Acid", "section": "ingredients", "cas": "59-30-3"},
  {"id": "phosphatidylserine", "name": "Phosphatidylserine", "section": "ingredients", "cas": "51446-62-9"},
  {"id": "phosphatidylcholine", "name": "Phosphatidylcholine", "section": "ingredients", "cas": "8002-43-5"},
  {"id": "melatonin", "name": "Melatonin", "section": "ingredients", "cas": "73-31-4"},
  {"id": "lactulose", "name": "Lactulose", "section": "ingredients", "cas": "4618-18-2"},
  {"id": "gamma-aminobutyric-acid", "name": "Gamma Aminobutyric Acid", "section": "ingredients", "cas": "56-12-2"},
  {"id": "inositol-nicotinate", "name": "Inositol Nicotinate", "section": "ingredients", "cas": "6556-11-2"},
  {"id": "guanidinoacetic-acid", "name": "Guanidinoacetic Acid", "section": "ingredients", "cas": "352-97-6"},
  {"id": "tranexamic-acid", "name": "Tranexamic Acid", "section": "ingredients", "cas": "1197-18-8"},
  {"id": "coconut-oil", "name": "Coconut Oil", "section": "ingredients", "cas": "8001-31-8"},
  {"id": "luteolin", "name": "Luteolin", "section": "ingredients", "cas": "491-70-3"},
  {"id": "phytoene", "name": "Phytoene", "section": "ingredients", "cas": "13920-14-4", "casForms": [{"label": "15-cis", "cas": "13920-14-4"}, {"label": "all-trans", "cas": "540-04-5"}]},
  {"id": "betadex-sulfobutyl-ether-sodium", "name": "Betadex Sulfobutyl Ether Sodium", "section": "excipients", "cas": "182410-00-0"},
  {"id": "hydroxypropyl-beta-cyclodextrin", "name": "Hydroxypropyl-beta-cyclodextrin", "section": "excipients", "cas": "128446-35-5"},
  {"id": "beta-cyclodextrin", "name": "Beta-Cyclodextrin", "section": "excipients", "cas": "7585-39-9"},
  {"id": "sodium-starch-glycolate", "name": "Sodium Starch Glycolate", "section": "excipients", "cas": "9063-38-1"},
  {"id": "gamma-cyclodextrin", "name": "Gamma-Cyclodextrin", "section": "excipients", "cas": "17465-86-0"},
  {"id": "hpmc-e-3-e-5-e-15", "name": "HPMC E-3/E-5/E-15", "section": "excipients", "cas": "9004-65-3"},
  {"id": "pvp-k-30-k-90", "name": "PVP K-30/K-90", "section": "excipients", "cas": "9003-39-8"},
  {"id": "sodium-stearyl-fumarate", "name": "Sodium Stearyl Fumarate", "section": "excipients", "cas": "4070-80-8"},
  {"id": "microcrystalline-cellulose", "name": "Microcrystalline cellulose", "section": "excipients", "cas": "9004-34-6"},
  {"id": "salcaprozate-sodium", "name": "Salcaprozate sodium", "section": "excipients", "cas": "203787-91-1"},
  {"id": "tetrabutylammonium-bromide", "name": "Tetrabutylammonium Bromide", "section": "others", "cas": "1643-19-2"},
  {"id": "p-hydroxybenzoic-acid", "name": "p-Hydroxybenzoic Acid", "section": "others", "cas": "99-96-7"},
  {"id": "n-boc-3-pyrrolidinone", "name": "N-Boc-3-pyrrolidinone", "section": "others", "cas": "101385-93-7"},
  {"id": "2-chlorophenothiazine", "name": "2-Chlorophenothiazine", "section": "others", "cas": "92-39-7"},
  {"id": "tert-butyl-bromoacetate", "name": "Tert-Butyl bromoacetate", "section": "others", "cas": "5292-43-3"},
  {"id": "folcisteine", "name": "Folcisteine", "section": "others", "cas": "5025-82-1"},
  {"id": "2-bromopropionic-acid", "name": "2-Bromopropionic acid", "section": "others", "cas": "598-72-1"},
  {"id": "isopropyl-myristate", "name": "Isopropyl myristate", "section": "others", "cas": "110-27-0"},
  {"id": "hcg", "name": "HCG", "section": "others", "cas": "9002-61-3"},
  {"id": "triisopropylsilane", "name": "Triisopropylsilane", "section": "others", "cas": "6485-79-6"},
  {"id": "ampd", "name": "AMPD", "section": "others", "cas": "115-69-5"},
  {"id": "temed-n-n-n-n-tetramethylethylenediamine", "name": "TEMED (N,N,N',N'- Tetramethylethylenediamine)", "section": "others", "cas": "110-18-9"},
  {"id": "2-4-bis-1-1-biphenyl-4-yl-6-chloro-1-3-5-triazine", "name": "2,4-Bis([1,1'-biphenyl]-4-yl)-6-chloro-1,3,5-triazine", "section": "others", "cas": "182918-13-4"},
  {"id": "5-ala-5-aminolevulinic-acid-hydrochloride", "name": "5-ALA (5-Aminolevulinic acid hydrochloride)", "section": "others", "cas": "5451-09-2"},
  {"id": "ammonium-calcium-sodium-magnesium-potassium-lignosulfonate", "name": "Ammonium/Calcium/Sodium/Magnesium/Potassium lignosulfonate", "section": "others", "cas": "8061-53-8", "shortName": "Lignosulfonate (Ca/Na/Mg/K/NH4)"},
  {"id": "zineb", "name": "Zineb", "section": "others", "cas": "12122-67-7"},
  {"id": "hmg", "name": "HMG", "section": "others", "cas": "61489-71-2"},
  {"id": "n-acetyl-l-cysteine", "name": "N-Acetyl-L-cysteine", "section": "apis", "cas": "616-91-1", "therapeuticSegment": "Respiratory / Steroids"},
  {"id": "budesonide", "name": "Budesonide", "section": "apis", "cas": "51333-22-3", "therapeuticSegment": "Respiratory / Steroids"},
  {"id": "heparin-sodium", "name": "Heparin Sodium", "section": "apis", "cas": "9041-08-1", "therapeuticSegment": "Anticoagulants"},
  {"id": "enoxaparin-sodium", "name": "Enoxaparin Sodium", "section": "apis", "cas": "679809-58-6", "therapeuticSegment": "Anticoagulants"},
];

export const pharmaById = (id: string) => pharmaProducts.find((p) => p.id === id);
